### PR TITLE
net: ethernet: dm9000: Accept a MAC address as a bootarg for CI20.

### PR DESCRIPTION
**Pull request by HarveyHunt**
The MAC address for the CI20's DM9000 is stored in EEPROM on a different
part of the board. Previously, the DM9000 would make up a random MAC
after failing to read its own EEPROM. This commit makes it possible for
U-BOOT to pass the MAC address to the DM9000 driver. Such as:

bootargs="dm9000.mac_addr=${ethaddr}"

Note: This isn't the "correct" way to do this, but will do for now. The correct method would be to recompile U-BOOT with `CONFIG_OF_LIBFDT` and `CONFIG_FIT` enabled. Then the kernel should be compiled as a FIT image and U-BOOT can then add an entry to the DM9000's DT node to set the MAC address (`local-mac-address = [xx xx xx xx xx xx];`).

### CODE REVIEW

**Comment by aejsmith** [comment]
Probably worth adding a note to the commit message that this is not a final solution and in the long run the "correct" way to do it would be via DT.

**Comment by ZubairLK** [comment]
And a signed off line perhaps.

**Comment by HarveyHunt** [comment]
Done and done. :-)

**Comment by aejsmith** [comment]
The note is in the pull request message but not the actual commit message :)

Better to have it in the commit itself so anyone who sees that but not the pull request knows it's only intended to be temporary.

**Comment by HarveyHunt** [comment]
@aejsmith You're right, I had a brainfart - I'll add it now.

**Pull request merged**
