### PR TITLE
jz4740-mmc enhancements

### PR DESCRIPTION
**Pull request by pcercuei**
This pull request updates and enhances the upstream MMC driver (jz4740-mmc) so that it can be used on the ci20, instead of IMGTec's driver, which diverged from upstream.

All of those commits have been reported to work on both the GCW Zero (jz4770) and the CI20 (jz4780). They might work on the jz4740 provided a pinctrl driver exists.

More testing might be needed.

### CODE REVIEW

**Comment by HarveyHunt** [comment]
I've taken a look at this PR this afternoon and have come across something strange:

When running `root@ci20:~# dd if=/mnt/sd/test.bin of=/mnt/tmpfs/test.bin bs=4096` on the Ci20 using the JZ4780 driver and this one, the performance is the same.

When testing WiFi performance by running `iperf`, the JZ4780 driver achieves ~20Mbit/s, but this driver achieves ~7Mbit/s.

Is this something you've noticed?

**Comment by pcercuei** [comment]
The jz4740-mmc driver uses 24 MHz as the maximum frequency. The jz4780-mmc driver reads the maximum frequency from device tree; for the ci20, it is set at 48 MHz. This might be related.

**Comment by HarveyHunt** [comment]
I've just rebased against `ci20-v3.18` as it has #63 in it now, but there is no change.

I should have mentioned that I am using the following patch:

```
From 1ccd21117385b44baa917df76f2744c40c2ee328 Mon Sep 17 00:00:00 2001
From: Alex Smith <alex.smith@imgtec.com>
Date: Fri, 24 Jul 2015 12:37:39 +0100
Subject: [PATCH] mmc: jz4740: Set clock rate to mmc->f_max rather than
 JZ_MMC_CLK_RATE

The maximum clock rate can be overridden by DT. The clock rate should
be set to the DT-specified value rather than the constant JZ_MMC_CLK_RATE
when this is done. If the maximum clock rate is not set by DT then
mmc->f_max will be set to JZ_MMC_CLK_RATE.

Signed-off-by: Alex Smith <alex.smith@imgtec.com>
---
 drivers/mmc/host/jz4740_mmc.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/drivers/mmc/host/jz4740_mmc.c b/drivers/mmc/host/jz4740_mmc.c
index e0969c39..57cb31c 100644
--- a/drivers/mmc/host/jz4740_mmc.c
+++ b/drivers/mmc/host/jz4740_mmc.c
@@ -796,7 +796,7 @@ static int jz4740_mmc_set_clock_rate(struct jz4740_mmc_host *host, int rate)
    int real_rate;

    jz4740_mmc_clock_disable(host);
-   clk_set_rate(host->clk, JZ_MMC_CLK_RATE);
+   clk_set_rate(host->clk, host->mmc->f_max);

    real_rate = clk_get_rate(host->clk);
```

The Ci20 uses 48Mhz for MSC0 (The SD card) and 24Mhz for MSC1 (WiFi).

**Comment by pcercuei** [comment]
The jz47xx driver forces the MMC_CAP_SDIO_IRQ flag, the jz4740 driver does not (and shouldn't).
Maybe it is related?

Does adding a "cap-sdio-irq" to the devicetree solve this?

**Comment by HarveyHunt** [comment]
I've tested this with `cap-sdio-irq` in DT and it is the same speed as our driver, so that was the problem. :-)

A couple of notes:
- `jz4740_mmc_set_clock_rate` should use `host->mmc->f_max` as the clock rate as this is pulled straight from DT.
- Can you make the driver not fail when it can't get the dma tx/rx ids from DT? Our DMA implementation doesn't need these to function correctly.

Thanks again :+1:

**Comment by pcercuei** [comment]
Should be OK now.

**Comment by HarveyHunt** [comment]
Thanks for the changes - looks good to me. We'll get this merged in soon. :+1:

**Pull request merged**
