### PR TITLE
Ci20 v3.18 bluetooth v2

### PR DESCRIPTION
**Pull request by mpredfearn**
Update the pull request to include fixes for the JZ4780 FIFO

These patches add an rfkill regulator to enable resetting the flaky bluetooth chip on the CI20.
Add the regulator to the CI20's DT.
Fix the hardware flow control in the UART driver
Fix the FIFO mode in the UART driver

### CODE REVIEW

**Comment by pcercuei** [comment]
The last commit's message mentions the JN4780; I believe you meant JZ4780.
Are the TX/RX FIFOs only supported on the JZ4780? Not on earlier versions?

**Comment by mpredfearn** [comment]
AFAIK There are smaller FIFOs of differing sizes in the older devices but I don't currently have other devices available to ensure that driver modifications are correct...

**Comment by ZubairLK** [comment]
These need a rebase due to latest changes. probably just dt nodes formatting.
And any fixes based on feedback/review. j'n'4780 perhaps

**Comment by ZubairLK** [comment]
pushed directly

**Pull request closed without merging**
